# == global config ==
SEED: 2024  # random seed
DEVICE: cuda  # device to be used
MIXED_PRECISION: false  # whether to use mixed-16 precision
OUTPUT_DIR: /kaggle/working/  # output folder

# == data config ==
DATA_ROOT: /home/ybouaouni/workspace/Training/CLEF/data/bird-clef-2024  # root folder
PREPROCESSED_DATA_ROOT: /home/ybouaouni/workspace/Training/CLEF/data/bird-clef-2024-5s-mel
LOAD_DATA: true  # whether to load data from pre-processed dataset
FS: 32000  # sample rate
N_FFT: 1095  # n FFT of Spec.
WIN_SIZE: 412  # WIN_SIZE of Spec.
WIN_LAP: 100  # overlap of Spec.
MIN_FREQ: 40  # min frequency
MAX_FREQ: 15000  # max frequency

# == model config ==
MODEL_TYPE: efficientnet_b0  # model type

# == dataset config ==
BATCH_SIZE: 32  # batch size of each step
N_WORKERS: 4  # number of workers

# == AUG ==
USE_XYMASKING: true  # whether use XYMasking

# == training config ==
FOLDS: 10  # n fold
EPOCHS: 15  # max epochs
LR: 0.001  # learning rate
WEIGHT_DECAY: 1e-5  # weight decay of optimizer

# == other config ==
VISUALIZE: true  # whether to visualize data and batch
